require("plugins.plugins")
require("configs.settings")
require("configs.tmux")
require("configs.treesitter")
require("configs.harpoon")
require("configs.undotree")
require("configs.lspzero")
require("configs.prettier")
-- require("configs.coc")

